exports.serverResponseMessage = {
  // Common Messages
  CONNECTED_WITH_DB: "Connected with database successfully",
  UNABLE_TO_VERIFY_REQUEST_DATA: "UNABLE_TO_VERIFY_REQUEST_DATA",
  SESSION_EXPIRE: "SESSION_EXPIRE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN:'FORBIDDEN',
  RECORD_CREATED: "RECORD_CREATED",
  RECORD_UPDATED: "RECORD_UPDATED",
  RECORD_DELETED: "RECORD_DELETED",
  RECORD_FETCHED: "RECORD_FETCHED",
  RECORD_DOES_NOT_EXISTS: "RECORD_DOES_NOT_EXISTS",
  RECORD_ALREADY_EXISTS: "RECORD_ALREADY_EXISTS",
  
  // Common Error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
