exports.serverResponseMessage = {
  // Common Messages
  CONNECTED_WITH_DB: "Connected with database successfully",
  UNABLE_TO_VERIFY_REQUEST_DATA: "UNABLE_TO_VERIFY_REQUEST_DATA",
  SESSION_EXPIRE: "SESSION_EXPIRE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN:'FORBIDDEN',
  RECORD_CREATED: "RECORD_CREATED",
  RECORD_UPDATED: "RECORD_UPDATED",
  RECORD_DELETED: "RECORD_DELETED",
  RECORD_FETCHED: "RECORD_FETCHED",
  RECORD_DOES_NOT_EXISTS: "RECORD_DOES_NOT_EXISTS",
  RECORD_ALREADY_EXISTS: "RECORD_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
  UNABLE_TO_CREATE_USER: "UNABLE_TO_CREATE_USER",
  UNABLE_TO_UPDATE_USER: "UNABLE_TO_UPDATE_USER",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  MOBILE_NUMBER_EXISTS: "MOBILE_NUMBER_EXISTS",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_USER_CRED: "INVALID_USER_CRED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  EMAIL_VERIFICATION_MAIL: "EMAIL_VERIFICATION_MAIL",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  
  //Auth Messages
  LOGIN_SUCCESSFULLY: "LOGIN_SUCCESSFULLY",
  LOGOUT_SUCCESSFULLY: "LOGOUT_SUCCESSFULLY",
  OLD_PASSWORD_INCORRECT: "OLD_PASSWORD_INCORRECT",
  PASSWORD_RESET_SUCCESSFULLY: "PASSWORD_RESET_SUCCESSFULLY",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_SET_NEW_FAILED: "FORGOT_PASSWORD_SET_NEW_FAILED",
  FORGOT_PASSWORD_SET_NEW_SUCCESS: "FORGOT_PASSWORD_SET_NEW_SUCCESS",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  USER_CREATED_SUCCESSFULLY: "USER_CREATED_SUCCESSFULLY",
  USER_UPDATED_SUCCESSFULLY: "USER_UPDATED_SUCCESSFULLY",
  
  // Common Error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Country Error
  COUNTRY_NAME_EXISTS: "COUNTRY_NAME_EXISTS",
  COUNTRY_CODE_EXISTS: "COUNTRY_CODE_EXISTS"
};
