const { JOI_ERROR } = require("../utils/constants");

exports.serverResponseMessage = {
  // Common Messages
  CONNECTED_WITH_DB: "Connected with database successfully",
  UNABLE_TO_VERIFY_REQUEST_DATA: "UNABLE_TO_VERIFY_REQUEST_DATA",
  SESSION_EXPIRE: "SESSION_EXPIRE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RECORD_CREATED: "RECORD_CREATED",
  RECORD_UPDATED: "RECORD_UPDATED",
  RECORD_DELETED: "RECORD_DELETED",
  RECORD_FETCHED: "RECORD_FETCHED",
  RECORD_DOES_NOT_EXISTS: "RECORD_DOES_NOT_EXISTS",
  RECORD_ALREADY_EXISTS: "RECORD_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
  UNABLE_TO_CREATE_USER: "UNABLE_TO_CREATE_USER",
  UNABLE_TO_UPDATE_USER: "UNABLE_TO_UPDATE_USER",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  MOBILE_NUMBER_EXISTS: "MOBILE_NUMBER_EXISTS",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_USER_CRED: "INVALID_USER_CRED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  EMAIL_VERIFICATION_MAIL: "EMAIL_VERIFICATION_MAIL",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  INVALID_MULTILINGUAL_DATA: "INVALID_MULTILINGUAL_DATA",
  PLEASE_DISABLE_SUB_CATEGORY_TO_DISABLE_MAIN_CATEGORY:
    "PLEASE_DISABLE_SUB_CATEGORY_TO_DISABLE_MAIN_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_TO_DISABLE_MAIN_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_TO_DISABLE_MAIN_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_AND_SUB_CATEGORY_TO_DISABLE_MAIN_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_AND_SUB_CATEGORY_TO_DISABLE_MAIN_CATEGORY",
  PLEASE_DISABLE_CHILD_CATEGORY_TO_DISABLE_SUB_CATEGORY:
    "PLEASE_DISABLE_CHILD_CATEGORY_TO_DISABLE_SUB_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_TO_DISABLE_SUB_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_TO_DISABLE_SUB_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_AND_CHILD_CATEGORY_TO_DISABLE_SUB_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_AND_CHILD_CATEGORY_TO_DISABLE_SUB_CATEGORY",
  PLEASE_DISABLE_SUB_CHILD_CATEGORY_TO_DISABLE_CHILD_CATEGORY:
    "PLEASE_DISABLE_SUB_CHILD_CATEGORY_TO_DISABLE_CHILD_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_TO_DISABLE_CHILD_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_TO_DISABLE_CHILD_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_AND_SUB_CHILD_CATEGORY_TO_DISABLE_CHILD_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_AND_SUB_CHILD_CATEGORY_TO_DISABLE_CHILD_CATEGORY",
  PLEASE_DISABLE_PRODUCTS_TO_DISABLE_SUB_CHILD_CATEGORY:
    "PLEASE_DISABLE_PRODUCTS_TO_DISABLE_SUB_CHILD_CATEGORY",

  //Auth Messages
  LOGIN_SUCCESSFULLY: "LOGIN_SUCCESSFULLY",
  LOGOUT_SUCCESSFULLY: "LOGOUT_SUCCESSFULLY",
  OLD_PASSWORD_INCORRECT: "OLD_PASSWORD_INCORRECT",
  PASSWORD_RESET_SUCCESSFULLY: "PASSWORD_RESET_SUCCESSFULLY",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_SET_NEW_FAILED: "FORGOT_PASSWORD_SET_NEW_FAILED",
  FORGOT_PASSWORD_SET_NEW_SUCCESS: "FORGOT_PASSWORD_SET_NEW_SUCCESS",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  USER_CREATED_SUCCESSFULLY: "USER_CREATED_SUCCESSFULLY",
  USER_UPDATED_SUCCESSFULLY: "USER_UPDATED_SUCCESSFULLY",


  //Our Story
  OUR_STORY_CREATED : "Story Created Successfully",
  OUR_STORY_EXIST : "Story Already Exist",
  OUR_STORY_NOT_EXIST : "Our Story Not Exist",
  OUR_STORY_UPDATED : "Our Story Updated Successfully",
  NO_STORY_FOUND: "No Story Found",
  STORY_FETCHED:"Story Fetched Successfully",
  STORY_DELETED:"Story Deleted Successfully",


   //Home Page
   HOME_CREATED : "Home Page Created Successfully",
   HOME_EXIST : "Home Page Already Exist",
   HOME_NOT_EXIST : "Home Page Not Exist",
   HOME_UPDATED : "Home Page Updated Successfully",
   HOME_FOUND: "No Home Page Found",
   HOME_FETCHED:"Home Page Fetched Successfully",
   HOME_DELETED:"Home Page Deleted Successfully",

  // Common Error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Country Error
  COUNTRY_NAME_EXISTS: "COUNTRY_NAME_EXISTS",
  COUNTRY_CODE_EXISTS: "COUNTRY_CODE_EXISTS",
  SLUG_EXISTS: "SLUG_EXISTS",
  COLOR_CODE_EXISTS: "COLOR_CODE_EXISTS",
  PRODUCT_TYPE_EXISTS: "PRODUCT_TYPE_EXISTS",
  GENDER_ALREADY_EXISTS: "GENDER_ALREADY_EXISTS",
  YARN_ID_ALREADY_EXISTS: "YARN_ID_ALREADY_EXISTS",
  [`${JOI_ERROR}_REQUIRED_SLUG`]: `${JOI_ERROR}_REQUIRED_SLUG`,
  [`${JOI_ERROR}_INVALID_SLUG`]: `${JOI_ERROR}_INVALID_SLUG`,
  [`${JOI_ERROR}_REQUIRED_GENDER`]: `${JOI_ERROR}_REQUIRED_GENDER`,
  [`${JOI_ERROR}_INVALID_GENDER`]: `${JOI_ERROR}_INVALID_GENDER`,
  [`${JOI_ERROR}_REQUIRED_MAIN_CATEGORY`]: `${JOI_ERROR}_REQUIRED_MAIN_CATEGORY`,
  [`${JOI_ERROR}_INVALID_MAIN_CATEGORY`]: `${JOI_ERROR}_INVALID_MAIN_CATEGORY`,
  [`${JOI_ERROR}_REQUIRED_SUB_CATEGORY`]: `${JOI_ERROR}_REQUIRED_SUB_CATEGORY`,
  [`${JOI_ERROR}_INVALID_SUB_CATEGORY`]: `${JOI_ERROR}_INVALID_SUB_CATEGORY`,
  [`${JOI_ERROR}_REQUIRED_CHILD_CATEGORY`]: `${JOI_ERROR}_REQUIRED_CHILD_CATEGORY`,
  [`${JOI_ERROR}_INVALID_CHILD_CATEGORY`]: `${JOI_ERROR}_INVALID_CHILD_CATEGORY`,
  [`${JOI_ERROR}_REQUIRED_SUB_CHILD_CATEGORY`]: `${JOI_ERROR}_REQUIRED_SUB_CHILD_CATEGORY`,
  [`${JOI_ERROR}_INVALID_SUB_CHILD_CATEGORY`]: `${JOI_ERROR}_INVALID_SUB_CHILD_CATEGORY`,
  [`${JOI_ERROR}_REQUIRED_PRODUCT_TYPE_CATEGORY`]: `${JOI_ERROR}_REQUIRED_PRODUCT_TYPE_CATEGORY`,
  [`${JOI_ERROR}_INVALID_PRODUCT_TYPE_CATEGORY`]: `${JOI_ERROR}_INVALID_PRODUCT_TYPE_CATEGORY`,
  [`${JOI_ERROR}_REQUIRED_SIZE`]: `${JOI_ERROR}_REQUIRED_SIZE`,
  [`${JOI_ERROR}_INVALID_SIZE`]: `${JOI_ERROR}_INVALID_SIZE`,
  [`${JOI_ERROR}_ANY_ONLY_STATUS`]: `${JOI_ERROR}_ANY_ONLY_STATUS`,
  [`${JOI_ERROR}_TYPE_STATUS`]: `${JOI_ERROR}_TYPE_STATUS`,
  [`${JOI_ERROR}_REQUIRED_STATUS`]: `${JOI_ERROR}_REQUIRED_STATUS`,
  [`${JOI_ERROR}_REQUIRED_PRICE`]: `${JOI_ERROR}_REQUIRED_PRICE`,

  PLEASE_DELETE_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_YARN_TO_DELETE_GENDER: "PLEASE_DELETE_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DELETE_GENDER",
  PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER:
    "PLEASE_DELETE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DELETE_GENDER",

  PLEASE_DISABLE_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_PRE_REGISTRATION_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_TO_DISABLE_GENDER",
  PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER:
    "PLEASE_DISABLE_MAIN_CATEGORY_SUB_CATEGORY_CHILD_CATEGORY_SUB_CHILD_CATEGORY_YARN_PRE_REGISTRATION_TO_DISABLE_GENDER",

  PLEASE_DELETE_YARN_TO_DELETE_COLOUR: "PLEASE_DELETE_YARN_TO_DELETE_COLOUR",
  PLEASE_DISABLE_YARN_TO_DISABLE_COLOUR:
    "PLEASE_DISABLE_YARN_TO_DISABLE_COLOUR",
  PLEASE_DELETE_YARN_TO_DELETE_MATERIAL:
    "PLEASE_DELETE_YARN_TO_DELETE_MATERIAL",
  PLEASE_DISABLE_YARN_TO_DISABLE_MATERIAL:
    "PLEASE_DISABLE_YARN_TO_DISABLE_MATERIAL",
  PLEASE_DELETE_YARN_TO_DELETE_OCCASSION:
    "PLEASE_DELETE_YARN_TO_DELETE_OCCASSION",
  PLEASE_DISABLE_YARN_TO_DISABLE_OCCASSION:
    "PLEASE_DISABLE_YARN_TO_DISABLE_OCCASSION",
  PLEASE_DELETE_YARN_TO_DELETE_PATTERN: "PLEASE_DELETE_YARN_TO_DELETE_PATTERN",
  PLEASE_DISABLE_YARN_TO_DISABLE_PATTERN:
    "PLEASE_DISABLE_YARN_TO_DISABLE_PATTERN",
  PLEASE_DELETE_YARN_TO_DELETE_PERCEIVED_WEIGHT:
    "PLEASE_DELETE_YARN_TO_DELETE_PERCEIVED_WEIGHT",
  PLEASE_DISABLE_YARN_TO_DISABLE_PERCEIVED_WEIGHT:
    "PLEASE_DISABLE_YARN_TO_DISABLE_PERCEIVED_WEIGHT",
  PLEASE_DELETE_YARN_TO_DELETE_SEASONALITY:
    "PLEASE_DELETE_YARN_TO_DELETE_SEASONALITY",
  PLEASE_DISABLE_YARN_TO_DISABLE_SEASONALITY:
    "PLEASE_DISABLE_YARN_TO_DISABLE_SEASONALITY",
  PLEASE_DISABLE_STEP_CARD_TO_DELETE_IT: "PLEASE_DISABLE_STEP_CARD_TO_DELETE_IT",
  PLEASE_DELETE_STEP_CARD_TO_DELETE_STEP_TYPE:
    "PLEASE_DELETE_STEP_CARD_TO_DELETE_STEP_TYPE",
};
